/**
 * The storefront catalogue.
 *
 * Products are ours, defined in data.json and regenerated by scripts/build-catalogue.mjs.
 * The bag is still Shopify's, so every one of our variants carries a *backing* mock.shop
 * variant id — the merchandise the cart is actually built from. lib/shopify/cart.ts maps
 * between the two, and nothing above this layer needs to know.
 *
 * The upstream demo store has no productType and no usable tags, which is why category
 * pages all rendered the same 29 items before this existed. Filtering here is plain
 * in-memory work over 90 products: no query language, no network, and no reason for a
 * listing to disagree with a detail page.
 */

import { absoluteImageUrl, absoluteUrl } from "@/lib/api/url"
import { productPath } from "@/lib/routes"
import raw from "./data.json"
import type { Product, ProductImage, ProductVariant } from "@/lib/shopify/types"

type RawVariant = { size: string; color: string; backingId: string }

type RawProduct = {
  handle: string
  title: string
  productType: string
  tags: string[]
  description: string
  price: string
  compareAt: string | null
  currencyCode: string
  image: { url: string; altText: string | null; width: number | null; height: number | null } | null
  sizes: string[]
  colors: string[]
  variants: RawVariant[]
}

const DATA = raw as { source: string; currencyCode: string; products: RawProduct[] }

const slug = (value: string) =>
  value.toLowerCase().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "")

/** Our own id space, so a local id is never mistaken for a Shopify one. */
export const productGid = (handle: string) => `gid://glowa/Product/${handle}`
export const variantGid = (handle: string, size: string, color: string) =>
  `gid://glowa/ProductVariant/${handle}:${slug(size)}:${slug(color)}`

/** True for ids this module minted. Anything else belongs to Shopify and passes through. */
export const isLocalVariantId = (id: string) => id.startsWith("gid://glowa/ProductVariant/")

/**
 * Products with no upstream photograph render a generated card instead.
 *
 * mock.shop's imagery is entirely apparel, so there is nothing to stand in for a
 * lipstick or a vase. A card that names the product is honest; a hoodie photograph on a
 * homeware listing just looks broken.
 */
const placeholderImage = (product: RawProduct): ProductImage => ({
  url: `/api/placeholder/${product.handle}`,
  altText: product.title,
  width: 900,
  height: 1200,
})

function toImage(product: RawProduct): ProductImage {
  const base = product.image ?? placeholderImage(product)
  return { ...base, url: absoluteImageUrl(base.url) }
}

function toVariants(product: RawProduct): ProductVariant[] {
  const price = { amount: product.price, currencyCode: product.currencyCode }
  const compareAtPrice = product.compareAt
    ? { amount: product.compareAt, currencyCode: product.currencyCode }
    : null

  return product.variants.map((v) => ({
    id: variantGid(product.handle, v.size, v.color),
    // Shopify's own convention, which the cart UI already formats around.
    title: [v.size, v.color].join(" / "),
    availableForSale: true,
    selectedOptions: [
      { name: "Size", value: v.size },
      { name: "Color", value: v.color },
    ],
    price,
    compareAtPrice,
  }))
}

/** Built once: the catalogue is static, so there is nothing to invalidate. */
const PRODUCTS: Product[] = DATA.products.map((p) => {
  const image = toImage(p)
  const price = { amount: p.price, currencyCode: p.currencyCode }
  const compareAt = { amount: p.compareAt ?? p.price, currencyCode: p.currencyCode }

  return {
    id: productGid(p.handle),
    handle: p.handle,
    url: absoluteUrl(productPath(p.handle)),
    title: p.title,
    description: p.description,
    descriptionHtml: `<p>${p.description}</p>`,
    productType: p.productType,
    tags: p.tags,
    availableForSale: true,
    featuredImage: image,
    images: [image],
    options: [
      { id: `${productGid(p.handle)}/Size`, name: "Size", values: p.sizes },
      { id: `${productGid(p.handle)}/Color`, name: "Color", values: p.colors },
    ],
    variants: toVariants(p),
    priceRange: { minVariantPrice: price, maxVariantPrice: price },
    compareAtPriceRange: { minVariantPrice: compareAt, maxVariantPrice: compareAt },
  }
})

const BY_HANDLE = new Map(PRODUCTS.map((p) => [p.handle, p]))

/** Local variant id -> the mock.shop variant the cart line is really built from. */
const BACKING_BY_VARIANT = new Map<string, string>()
/** Local variant id -> the product it belongs to, for restoring a cart line. */
const PRODUCT_BY_VARIANT = new Map<string, Product>()

for (const p of DATA.products) {
  const product = BY_HANDLE.get(p.handle)!
  for (const v of p.variants) {
    const id = variantGid(p.handle, v.size, v.color)
    BACKING_BY_VARIANT.set(id, v.backingId)
    PRODUCT_BY_VARIANT.set(id, product)
  }
}

export function allProducts(): Product[] {
  return PRODUCTS
}

export function productByHandle(handle: string): Product | null {
  return BY_HANDLE.get(handle) ?? null
}

export function backingVariantFor(localVariantId: string): string | null {
  return BACKING_BY_VARIANT.get(localVariantId) ?? null
}

/** The product and variant behind a local variant id, for rebuilding a cart line. */
export function resolveVariant(
  localVariantId: string,
): { product: Product; variant: ProductVariant } | null {
  const product = PRODUCT_BY_VARIANT.get(localVariantId)
  if (!product) return null
  const variant = product.variants.find((v) => v.id === localVariantId)
  return variant ? { product, variant } : null
}

export function productsByType(productType: string): Product[] {
  return PRODUCTS.filter((p) => p.productType.toLowerCase() === productType.toLowerCase())
}

export function productsByTag(tag: string): Product[] {
  return PRODUCTS.filter((p) => p.tags.some((t) => t.toLowerCase() === tag.toLowerCase()))
}

/**
 * Free text search across the fields a shopper would actually type.
 *
 * Every term has to match somewhere, so "black dress" narrows rather than widens — the
 * opposite of an OR, which on a 90 product catalogue returns most of it.
 */
export function searchProducts(query: string): Product[] {
  const terms = query.toLowerCase().split(/\s+/).filter(Boolean)
  if (terms.length === 0) return PRODUCTS

  return PRODUCTS.filter((p) => {
    const haystack = [p.title, p.productType, p.description, ...p.tags, ...p.options.flatMap((o) => o.values)]
      .join(" ")
      .toLowerCase()
    return terms.every((term) => haystack.includes(term))
  })
}
